version = 1

test_patterns = [
  "**/*_test.go"
]

exclude_patterns = [
  "vendor/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/stripe/smokescreen"
  dependencies_vendored = true
